const images = {
  home: {
    home1: require('./Home/main.png'),
    home2: require('./Home/image.png'),
    home3: require('./Home/image2.png'),
  },
  men: {
    cloth1: require('./Men/Clothes/shirt1.jpg'),
    cloth2: require('./Men/Clothes/shirt2.jpg'),
    cloth3: require('./Men/Clothes/shirt3.jpg'),
    shoes1: require('./Men/Shoes/shoes1.jpg'),
    shoes2: require('./Men/Shoes/shoes2.jpg'),
    shoes3: require('./Men/Shoes/shoes3.jpg'),
    newItem1: require('./Men/New/new1.jpg'),
    newItem2: require('./Men/New/new2.jpg'),
    newItem3: require('./Men/New/new3.jpg'),
    accessories1: require('./Men/Accessories/Accessories1.png'),
    accessories2: require('./Men/Accessories/Accessories2.png'),
    accessories3: require('./Men/Accessories/Accessories3.png'),
  },
  women: {
    cloth1: require('./Women/Clothes/shirt1.jpg'),
    cloth2: require('./Women/Clothes/shirt2.jpg'),
    cloth3: require('./Women/Clothes/shirt3.jpg'),
    shoes1: require('./Women/Shoes/shoes1.jpg'),
    shoes2: require('./Women/Shoes/shoes2.jpg'),
    shoes3: require('./Women/Shoes/shoes3.jpg'),
    newItem1: require('./Women/New/new1.jpg'),
    newItem2: require('./Women/New/new2.jpg'),
    newItem3: require('./Women/New/new3.jpg'),
    accessories1: require('./Women/Accessories/Accessories1.png'),
    accessories2: require('./Women/Accessories/Accessories2.png'),
    accessories3: require('./Women/Accessories/Accessories3.png'),
  },
  children: {
    cloth1: require('./Children/Clothes/shirt1.jpg'),
    cloth2: require('./Children/Clothes/shirt2.jpg'),
    cloth3: require('./Children/Clothes/shirt3.jpg'),
    shoes1: require('./Children/Shoes/shoes1.jpg'),
    shoes2: require('./Children/Shoes/shoes2.jpg'),
    shoes3: require('./Children/Shoes/shoes3.jpg'),
    newItem1: require('./Children/New/new1.jpg'),
    newItem2: require('./Children/New/new2.jpg'),
    newItem3: require('./Children/New/new3.jpg'),
    accessories1: require('./Children/Accessories/Accessories1.png'),
    accessories2: require('./Children/Accessories/Accessories2.png'),
    accessories3: require('./Children/Accessories/Accessories3.png'),
  },
};

export default images;
