import images from '../Assets/Images';

const products = {
  men: {
    newProducts: {
      label: 'New Products',
      data: [
        {
          id: 'product1',
          name: 'Stylish Jacket',
          price: 99.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.newItem1,
        },
        {
          id: 'product2',
          name: 'Classic Sneakers',
          price: 79.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.newItem2,
        },
        {
          id: 'product3',
          name: 'Trendy Backpack',
          price: 49.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.newItem3,
        },
      ],
    },
    shirts: {
      label: 'Shirts',
      data: [
        {
          id: 'shirt1',
          name: 'Casual Shirt',
          price: 29.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.cloth1,
        },
        {
          id: 'shirt2',
          name: 'Formal Shirt',
          price: 49.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.cloth2,
        },
        {
          id: 'shirt3',
          name: 'Graphic Tee',
          price: 19.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.cloth3,
        },
      ],
    },
    shoes: {
      label: 'Shoes',
      data: [
        {
          id: 'shoes1',
          name: 'Running Shoes',
          price: 89.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.shoes1,
        },
        {
          id: 'shoes2',
          name: 'Loafers',
          price: 59.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.shoes2,
        },
        {
          id: 'shoes3',
          name: 'Sandals',
          price: 39.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.shoes3,
        },
      ],
    },
    accessories: {
      label: 'Accessories',
      data: [
        {
          id: 'accessory1',
          name: 'Leather Belt',
          price: 29.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.accessories1,
        },
        {
          id: 'accessory2',
          name: 'Wrist Watch',
          price: 99.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.accessories2,
        },
        {
          id: 'accessory3',
          name: 'Sunglasses',
          price: 49.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.men.accessories3,
        },
      ],
    },
  },
  women: {
    newProducts: {
      label: 'New Products',
      data: [
        {
          id: 'product1',
          name: 'Stylish Jacket',
          price: 99.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.newItem1,
        },
        {
          id: 'product2',
          name: 'Classic Sneakers',
          price: 79.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.newItem2,
        },
        {
          id: 'product3',
          name: 'Trendy Backpack',
          price: 49.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.newItem3,
        },
      ],
    },
    shirts: {
      label: 'Shirts',
      data: [
        {
          id: 'shirt1',
          name: 'Casual Shirt',
          price: 29.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.cloth1,
        },
        {
          id: 'shirt2',
          name: 'Formal Shirt',
          price: 49.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.cloth2,
        },
        {
          id: 'shirt3',
          name: 'Graphic Tee',
          price: 19.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.cloth3,
        },
      ],
    },
    shoes: {
      label: 'Shoes',
      data: [
        {
          id: 'shoes1',
          name: 'Running Shoes',
          price: 89.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.shoes1,
        },
        {
          id: 'shoes2',
          name: 'Loafers',
          price: 59.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.shoes2,
        },
        {
          id: 'shoes3',
          name: 'Sandals',
          price: 39.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.shoes3,
        },
      ],
    },
    accessories: {
      label: 'Accessories',
      data: [
        {
          id: 'accessory1',
          name: 'Leather Belt',
          price: 29.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.accessories1,
        },
        {
          id: 'accessory2',
          name: 'Wrist Watch',
          price: 99.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.accessories2,
        },
        {
          id: 'accessory3',
          name: 'Sunglasses',
          price: 49.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.women.accessories3,
        },
      ],
    },
  },
  children: {
    newProducts: {
      label: 'New Products',
      data: [
        {
          id: 'product1',
          name: 'Stylish Jacket',
          price: 99.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.newItem1,
        },
        {
          id: 'product2',
          name: 'Classic Sneakers',
          price: 79.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.newItem2,
        },
        {
          id: 'product3',
          name: 'Trendy Backpack',
          price: 49.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.newItem3,
        },
      ],
    },
    shirts: {
      label: 'Shirts',
      data: [
        {
          id: 'shirt1',
          name: 'Casual Shirt',
          price: 29.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.cloth1,
        },
        {
          id: 'shirt2',
          name: 'Formal Shirt',
          price: 49.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.cloth2,
        },
        {
          id: 'shirt3',
          name: 'Graphic Tee',
          price: 19.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.cloth3,
        },
      ],
    },
    shoes: {
      label: 'Shoes',
      data: [
        {
          id: 'shoes1',
          name: 'Running Shoes',
          price: 89.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.shoes1,
        },
        {
          id: 'shoes2',
          name: 'Loafers',
          price: 59.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.shoes2,
        },
        {
          id: 'shoes3',
          name: 'Sandals',
          price: 39.99,
          sizes: ['S', 'M', 'L'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.shoes3,
        },
      ],
    },
    accessories: {
      label: 'Accessories',
      data: [
        {
          id: 'accessory1',
          name: 'Leather Belt',
          price: 29.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.accessories1,
        },
        {
          id: 'accessory2',
          name: 'Wrist Watch',
          price: 99.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.accessories2,
        },
        {
          id: 'accessory3',
          name: 'Sunglasses',
          price: 49.99,
          sizes: ['One Size'],
          colors: ['Black', 'White', 'Other'],
          images: images.children.accessories3,
        },
      ],
    },
  },
};

export default products;
